apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: onboarding
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - onboarding.example.com
  rules:
    - host: onboarding.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: onboarding
              servicePort: http
